# Generated by Django 2.2.24 on 2026-02-11 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0013_classproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='educationalproduct',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=20),
        ),
        migrations.AddField(
            model_name='educationalproduct',
            name='suggested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='educationalproduct',
            name='suggested_for_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_suggestions', to='survey.Class'),
        ),
        migrations.AlterField(
            model_name='educationalproduct',
            name='activity_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='educationalproduct',
            name='content_source',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='educationalproduct',
            name='educational_code',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='educationalproduct',
            name='info',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='educationalproduct',
            name='media_format',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
