# Generated by Django 2.2.24 on 2026-02-12 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0014_auto_20260211_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalproduct',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='educationalproduct',
            name='status',
        ),
        migrations.RemoveField(
            model_name='educationalproduct',
            name='suggested_for_class',
        ),
        migrations.AlterField(
            model_name='educationalproduct',
            name='suggested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProductSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('info', models.CharField(max_length=2000)),
                ('link', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('intelligences', models.ManyToManyField(related_name='suggested_intelligences', to='survey.StudyOption')),
                ('styles', models.ManyToManyField(related_name='suggested_styles', to='survey.StudyOption')),
                ('suggested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('suggested_for_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.Class')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='survey.EducationalType')),
            ],
        ),
    ]
